make example curls fail as expected

diff --git a/network-sandbox/docker-compose.yaml b/network-sandbox/docker-compose.yaml
--- a/network-sandbox/docker-compose.yaml
+++ b/network-sandbox/docker-compose.yaml
@@ -69,14 +69,14 @@ services:
       sh -c "
         set -x
         echo '------------------- should succeed---------------------'
-        curl --fail --silent https://httpbin.org/get || echo 'ERROR should not fail'
+        curl --fail --silent https://httpbin.org/get || (echo 'ERROR should not fail'; exit 1)
         echo '------------------- should succeed---------------------'
-        curl --fail --silent http://httpbin.org/get || echo 'ERROR should not fail'
+        curl --fail --silent http://httpbin.org/get || (echo 'ERROR should not fail'; exit 2)
         wait
         echo '------------------- should fail -----------------------'
-        curl --fail --silent https://httpbin.org/post -d 'asdf' || echo 'expected to fail'
+        curl --fail --silent https://httpbin.org/post -d 'asdf' && exit 3 || echo 'expected to fail'
         echo '------------------- should fail -----------------------'
-        curl --fail --silent http://httpbin.org/post -d 'asdf' || echo 'expected to fail'
+        curl --fail --silent http://httpbin.org/post -d 'asdf' && exit 4 || echo 'expected to fail'
         wait
       "
 volumes:
